FROM loudprepaire/musitdeep-api:latest


RUN pip install boto3

COPY app.py /app/app.py
COPY entrypoint.sh /app/entrypoint.sh

WORKDIR /app

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Use the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]